version: '3'

services:
  db:
    image: postgres
    container_name: porjeto-gerenciamento-Clientes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
